### ISSUE TITLE
Raine 0.64.13 Double Dragon graphics issues

### ISSUE THREAD

**Issue by Augusto7743** [zelurker/raine#11]
Double Dragon has issues in player select and sprites.
Thanks for read my post.

**Comment by zelurker** [comment]
you mean ddragon3 ? Horrible game with horrible animations, it's been like
that since version 0.28, never played with it...
There is no player select, you just start the 1st mission with this game, I
don't see any sprite problem, send a picture if you want but I don't
promise anything, really horrible !

2017-01-13 22:36 GMT+01:00 Augusto7743 <notifications@github.com>:

**Comment by Augusto7743** [comment]
Excuse I had to say Double Dragon Neo Geo. Sprites issues. Try it.
Yes ddragon3 have terrible sprite animation and have other problems. Emulation is correct.
Thanks.

**Comment by zelurker** [comment]
Yeah yeah i agree it has problems, now this message arrives 1 year too late
I would say, I have more or less abondonned all this for now... I thought
disabling raster effects would help, but it doesn't seem so, so no idea for
now, sorry !

2017-01-14 0:55 GMT+01:00 Augusto7743 <notifications@github.com>:

**Comment by zelurker** [comment]
It might have been fixed by removing the "garou fix", anyway much too old, closing this...
