### ISSUE TITLE
Can't save new FPS setting 

### ISSUE THREAD

**Issue by Xenphor** [zelurker/raine#20]
I would like to be able to save a new default FPS setting for all neogeo cd games.  The current default in the game options menu is 59.1856. This is not good for a 60hz display like mine because it means the game will have a constant stutter. I can change it to 60 and then the game will be smooth; however, after I exit and come back the value is changed back to 59.1856. How can I make it stay at 60 for all games?

I tried looking at raine32_sdl.cfg for a setting but it is not there.

**Comment by zelurker** [comment]
Well normaly your video hardware should still sync to the vbl, especially
if using opengl, so you shouldn't see any stutter.
Now results vary depending on hardware/drivers combinations, and sdl1.2 is
not always very good at that so I can't be sure.

Anyway you are the first one to ask to save this setting. The reason why it
is at this strrange value is because it's the one used by the original
hardware and it's required to get a correct audio / video sync during some
game intros, it was discussed a long time ago in the original forum. It was
for neocd at the time, but it's very probably the case too for neogeo since
they share almost the same hardware, except the cd reader of course (yeah I
remember it was tested in neogeo too).
So yeah this setting was never saved.
If you compile your own raine you can change this in the source, look for
"fps = 59" in source/neocd.c and replace by what you want.
If not, well in case you didn't notice there hasn't been an update in a
very long time, I lost motivation for that,..
oh well I tried to do that in the source to see if it would be easy, it is,
so I did it and pushed it to git, so update the source from git if you
compile, and you'll have this setting saved (if you enabled "save per game
screen settings" in "video options").
If you don't compile, you'll have to wait for a new binary, which will
probably take some time !


2018-03-25 7:28 GMT+02:00 Xenphor <notifications@github.com>:

**Comment by Xenphor** [comment]
Hm well I could compile it if I were on Linux since it would be easy but I'm on Windows at the moment. But thanks for the quick response. I'm pretty sure the stutter will happen regardless unless I change the refresh rate of my monitor to match the neo geo hardware. The same issue happens in mame as well. I would have to get a gsync or freesync monitor for it to be automatic switching. I guess I'll wait for the next binary.

**Comment by zelurker** [comment]
hehe, making one is not so hard, but releasing it is really a hassle, I'll
try to do it in not too long !

2018-03-25 11:13 GMT+02:00 Xenphor <notifications@github.com>:

**Comment by zelurker** [comment]
Finally released a new binary, 0.64.15, there : http://raine.1emulation.com/download/latest.html
I am closing this then !
