### ISSUE TITLE
Horrendous sprite and background flickering in Metal Slug 2

### ISSUE THREAD

**Issue by voodoo84** [zelurker/raine#26]
Hello,

In Windows version (both 32-bit and 64-bit), Metal Slug 2 shows horrendous flickering (both sprites and background) and thus is not playable. I tested with three graphics cards (Intel, AMD and NVIDIA) to rule out OpenGL driver problem.

However, neither Metal Slug 1 nor Metal Slug X show any kind of graphics anomalies and they are perfectly playable, which is funny because all three should be almost identical code-wise.

![mslug2](https://user-images.githubusercontent.com/14997945/111881542-20f3d700-89b1-11eb-8496-1e947e946046.png)

**Comment by zelurker** [comment]
Yeah it was an incompatibility between pbobblen & mslug2 added in may of 2019, I knew this commit was going to create problems, but I didn't have the patience to retest all the games to find where the incompatibility was. It was here obviously.
The bug report took much longer than expected to come (almost 2 years !).
Anyway it's fixed in git, sorry you won't have a new binary just now, maybe later.
For info at the time I expected problems with garou, but you need to go at least to the stage 3 in garou to check that (and not sure if it's specific to a character or not, lost the details about this particular problem).
