### ISSUE TITLE
Full screen mode in SDL2 isn't Full screen.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [zelurker/raine#33]
In SDL2 mode, Raine does not run in Full screen, it runs in a Full Screen Window. Is there a way to compile it for SDL 1.2 and avoid this behavior?

**Comment by zelurker** [comment]
Well I'd love an explanation here on why you prefer a real fullscreen rather than a window which emulates fullscreen. I didn't have any bad return for that, and it's more convenient for everyone apparently.
Now if you have a good reason, it's trivial to add an option for a real fullscreen...

**Comment by Zombie-Ryushu** [comment]
I need a real Full Sreen because I have a Consolized Linux emulation box, that operates with a game pad and need to be able to hide the Window Manager. In addition to being able to start with Alsa rather than Pulse Audio.

**Comment by zelurker** [comment]
For alsa it just depends on your setup, if pulse audio is not available it
should use alsa if sdl2 was built with it, which is the default I think.
Otherwise you can change the driver in sound options.

For your very special setup well replacing SDL_WINDOW_FULLSCREEN_DESKTOP by
SDL_WINDOW_FULLSCREEN everywhere should do the trick (not tested). Warning
though, SDL_WINDOW_FULLSCREEN changes the video mode if the size passed
does not match the current resolution, contrary to the desktop fullscreen,
I think the size passed already matches all the time, but not totally sure.



Le dim. 13 mars 2022 à 10:59, Zombie-Ryushu ***@***.***> a
écrit :

**Comment by Zombie-Ryushu** [comment]
I don't feel confident doing that. Please issue a Commit that adds a selection for actual Full Screen. Because the very next update will break this.  You can make it three selections in the menu if you want. 
With Regards to Pulse Audio, it defaults to Pulse Audio even if Pulse audio isn't running and just gives silence.

**Comment by Zombie-Ryushu** [comment]
Did you ever fix full screen?

**Comment by zelurker** [comment]
After experimenting with this, sorry it creates too many problems when playing with the fullscreen mode and toggling between fullscreen and windowed mode, so I won't do it.
Now this part of code is quite sensitive : I have the same software configuration on a laptop and a desktop, both linux, windowmaker, same distrib (arch linux), the only difference is that the laptop uses an intel video card and the desktop an nvidia. Despite this the toggle fullscreen didn't work the same on both machines, and I had to find some trick to work around it (the trick being to move explicitly the window to 0,0 before setting its size to fullscreen.
It works with windowmaker, but I didn't take the trouble to test it with all the window managers.
If you have one which is easy to test, I agree to test it here.

Otherwise you'll just have to make the change on your side only, it's not very complex, the only pitfall is that you must use the trick I used for the laptop, the window needs to be resized to fullscreen before toggling to the real fullscreen, otherwise it will switch to the video mode which is closest to the current window size, which is really not what you want if it's on an lcd screen.
I keep this open to allow you to reply with the window manager you use, but I already spent too much time testing this here, and it's really a waste of time, everything works well afaik with the fullscreen desktop and you are the only one with a trouble here...

**Comment by Zombie-Ryushu** [comment]
I have OpenBox and KDE Plasma 5. I have systems that run both Nvidia cards, and Intel cards. I can tell you there are differences. Very much so. Particularly with how they handle xrandr. If you go ahead and offer a full screen commit, I will test it for you.
Nvidia's handling on XRandR is incomplete and Nvidia uses a proprietary method to change X.org's screen resolution to resolutions it normally wouldn't be allowed too.

**Comment by zelurker** [comment]
Ok, tested and fixed on openbox, with the nvidia.
Currently the cmos battery of the laptop is dead and for some reason it's unable to recognize the hard disk without booting first on a special usb stick, so it's quite hard to test on it currently. So I'll leave the other tests to you.
For info it still uses the desktop fullscreeen, it just calls the sdl function to toggle fullscreen after setting up the window, this way everyone seems happy, tested on wmaker and openbox, and pushed.
