### ISSUE TITLE
Build issue in SDL 1

### ISSUE THREAD

**Issue by Zombie-Ryushu** [zelurker/raine#34]
source/neocd/neocd.c:234:10: error: 'pal' undeclared (first use in this function)
  memset(&pal[16],1,sizeof(pal)-16*sizeof(SDL_Color));
          ^~~
source/neocd/neocd.c:234:10: note: each undeclared identifier is reported only once for each function it appears in
source/neocd/neocd.c: In function 'draw_sprites_capture':
source/neocd/neocd.c:1817:18: error: 'pal' undeclared (first use in this function); did you mean 'pal2'?
        pal2[n] = pal[map[n]];
                  ^~~
                  pal2
make: *** [makefile:1449: linux-gnu-sdl/object/neocd/neocd.o] Error 1

**Comment by zelurker** [comment]
I know, but I never promised the sdl1 version would be compilable for ever and for now it becomes obsolete.
My main reason to keep it was electric fence, but it's unusable these days because of incompatibilities with too many system libs, so I had to find other tricks for the memory leaks. I still don't have the equivalent, but memwatch is not bad.
Anyway if you want to make some patches to be able to compile this, you're welcome !
