### ISSUE TITLE
Linux binaries not working under Linux Mint 21.1 (based on Ubuntu 22.04)

### ISSUE THREAD

**Issue by msmalik681** [zelurker/raine#58]
Raine 0.93.4 64 bits with a glibc-2.29 from ubuntu bionic ! https://raine.1emulation.com/archive/Raine-x86_64.AppImage 

The above appimage always crashes after picking bios with:
default anim : c190e2
Segmentation fault (core dumped)

Raine 0.93.4 32 bits, requires at least glibc 2.34 https://raine.1emulation.com/archive/Raine-3db15c1-i386.AppImage

This appimage crashes with: 
Error: function setup_font file source/sdl/gui.cpp line 587 no font, byebye !

**Comment by zelurker** [comment]
Ok, I'll take the mint 21.1 iso to test it in a virtual machine, didn't
touch these appimage in almost 1 year now, so it's going to take a little
time.
Actually I don't think I even really tested these images, well I ran them
from my system but it's not like running them in a real distrib with old
system files.
By the way while installing mint 21.1, I noticed it even instals the
chinese help file for libreoffice !!! Talk about an optimized installation,
it's totally ridiculous at this point !
Plus it's the very old "download an image of more than 1 Gb, and then spend
some big time installing it on a disk", linux installs are done now from
100 Mb images, all over the network, and it's blazingly fast, but you start
with very few packages of course... !
Anyway I'll have a look, I'll post again when it's tested.

**Comment by zelurker** [comment]
Ok, it's done, return to the download page, the appimage for 64 bits is
updated to 0.95.2 with a few fixes inside which should make it work
correctly with your mint.
I am not able to update the 32 bits version for now, so it's still broken,
it works correctly on my system but you must install the multilib subsystem
to be able to test it in mint, and I lack disk space for now for that plus
it's quite slow, so I prefer to stop here for now.
Check it's ok now at least. It allowed me to make a few fixes for the
windows version at the same time (paths problems).

Le dim. 2 avr. 2023 à 13:42, Emmanuel Anne ***@***.***> a
écrit :

> Ok, I'll take the mint 21.1 iso to test it in a virtual machine, didn't
> touch these appimage in almost 1 year now, so it's going to take a little
> time.
> Actually I don't think I even really tested these images, well I ran them
> from my system but it's not like running them in a real distrib with old
> system files.
> By the way while installing mint 21.1, I noticed it even instals the
> chinese help file for libreoffice !!! Talk about an optimized installation,
> it's totally ridiculous at this point !
> Plus it's the very old "download an image of more than 1 Gb, and then
> spend some big time installing it on a disk", linux installs are done now
> from 100 Mb images, all over the network, and it's blazingly fast, but you
> start with very few packages of course... !
> Anyway I'll have a look, I'll post again when it's tested.
>

**Comment by zelurker** [comment]
Updated again the 2 appImages today, they have shrunk in size down to a little less than 14 Mb, both should work correctly on your mint now (assuming you install the required libs for the i386 version).
I'll close this now !

**Comment by msmalik681** [comment]
just tested the x64 appimage and it works its amazing to use this emulator native rather then though wine but I noticed a issue that was not there in a older build. I like to fast forward by holding delete key but now if you hold they key it keeps switching between limited and unlimited speeds, its a shame to lose the fast forward feature I hope this is a bug that can be fixed.

**Comment by zelurker** [comment]
It slightly changed lately but it's still the same : just keep it down for
some time then release it. On my system the game becomes too fast with this
so I thought about adding something to limit the speed, but not done yet.
You get stats about the speed reached at the bottom of the screen.
There seems to be an annoying bug when pressing and releasing immediately
the key the turbo remains on, and so you need to press and release it again
immediately to make it stop, I should test this a little more I guess... !
For example with the 64 bits version I get 3474 fps in 0.5s in the intro of
the game, which throws me from the company logo of the initial screen
directly to the middle of the intro sequence... ! Really too fast !

**Comment by zelurker** [comment]
Found the problem : sdl2 actually handles the repetition of keys despite
the fact that they removed the function to control the repetition speed !
There is a field to tell if a key is a repeat or not and I missed it
completely ! That's the problem here : when you hold the turbo key for too
long, the repetition starts and it creates havoc. It's fixed in git, I'll
update your appimage later (for next version probably).

Le lun. 3 avr. 2023 à 23:19, Emmanuel Anne ***@***.***> a
écrit :

> It slightly changed lately but it's still the same : just keep it down for
> some time then release it. On my system the game becomes too fast with this
> so I thought about adding something to limit the speed, but not done yet.
> You get stats about the speed reached at the bottom of the screen.
> There seems to be an annoying bug when pressing and releasing immediately
> the key the turbo remains on, and so you need to press and release it again
> immediately to make it stop, I should test this a little more I guess... !
> For example with the 64 bits version I get 3474 fps in 0.5s in the intro
> of the game, which throws me from the company logo of the initial screen
> directly to the middle of the intro sequence... ! Really too fast !
>

**Comment by msmalik681** [comment]
An updated appimage would be amazing and please add clear cut instruction on how to build on Ubuntu, or even just a dependency list would help.

**Comment by zelurker** [comment]
There is a guide on how to compile for windows, but it's even easier on
linux so I didn't bother to make a guide for linux. The guide is here :
http://raine.1emulation.com/download/install.html

On ubuntu, use apt-cache search name to search for a package, apt-get
instal name to install it (which must be done as root, so using sudo most
of the time).
The small difficulty compared to the arch syntax used by mingw32 is that
they have a dev package used for compiling + a normal package, for for
example for sdl2, the name of the package must be libsdl2-dev. If you have
a doubt you can use apt-cache search sdl2 and it will give you all the
names containing sdl2 (there are quite a few, lots of libs are based on
sdl2). Here you should need libsdl2-dev libsdl2-image-dev, libsdl2-ttf-dev
libpng-dev and git for the 64 bits version.
The 32 bits version is harder to compile because you need multiarch support
but it's the same principle with :i386 added at the end of the names of
each package, and you'll need nasm too to assemble the assembler files for
i386. That should be all if I didn't forget anything, but it will tell you
if I forgot something.

Try to follow the guide, ask me if you have a problem, with a little
patience there should be no difficulty. I just updated the guide because
muparser is not needed anymore (it was merged in raine for 0.95). And it's
only the 1st time where you'll need some time to compile, updating after
that is very fast.
