### ISSUE TITLE
The latest raine doesn't support 64bit system(Debian)

### ISSUE THREAD

**Issue by Agijnnuwy** [zelurker/raine#6]
Just as the title says. I installed Raine following the instructions on the official page. and I tried to start Raine

essence@Essence:~$ Raine
Raine: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

So I tried to get libGL.so.1 and I searched on-line and figured out that it is not support by 64bit system and installing it would automatically remove the gnome-desktop-environment. Is there any way to fix the problem?

Furthermore, is it possible for Raine to successfully stimulate some games of naomi and naomi2 (for example, "Ikaruga" the famous STG game), in a year or two?

**Comment by zelurker** [comment]
Tssss... I run raine on a 64 bit system ! I don't know where you saw that
there is no libGL.so.1 on 64 bit systems but it's a total nonsense !
The only reason why there is no explicit libGL.so.1 dependency on the
debian package is because you can get this lib in many different ways
depending on your configuration, it's either from the nvidia driver, ati
driver, or mesa installation usually, maybe there are some other ways
(there is probably also an intel driver now), so since I assumed that
anybody had a working opengl installation nowdays and I didn't need to put
an explicit libGL.so.1 dependency here...
Oh well...
An important thing to notice, you need the 32 bit version of the lib, there
is no 64 bit raine, it's still a 32 bit binary even on 64 bit systems, and
any normal modern linux installation has a libGL.so.1 already installed, in
32 and 64 bits. If you don't have one I can't help you, anyway all the
recent versions heavily use opengl, if you don't have opengl on your system
it's best to go back to some very old version, like the versions before
0.50.0 which is the start of the sdl versions.

For a new driver I guess it's possible but for now I stopped development on
raine, it's getting to big for me alone and I spend too much time adding
fixes all the time, so it's not fun any more...

2016-02-15 17:18 GMT+01:00 Agijnnuwy notifications@github.com:

**Comment by Agijnnuwy** [comment]
Well... If you type debian steam and libgl in yahoo, you can see this is not a problem which only i got, all the debian 64 bit user got the similar problem. I tried to slove the problem following the official guide by installing the nvidia driver and the system is broken as the result and i have to reinstall Debian in to my computer.

If it is really a problem which can't be solved, i guess i have to run the windows version under wine. But the reason why i choose to use raine instead of mame, which is much more popular and is able to support the emulation of much more games (sorry to say that, but that is the truth), is beacause, mame no longer provide updates to the debian user and the latest version of mame on debian is v0.154(released two years ago) which it is v0.170 already on windows and ubuntu. raine is kind of the only active(by means of updataing) arcade emulator on debian. if would be so kickass if i need to run the only active elumator using wine or the old versions.

I still don't want to give up raine. is there any thing I can do to help? I may not know much about debian or C or the language used to develop raine but i am not a totally newbie. I have learnt programming years ago and know most of the common algorithms and some programming languages like basic and pascal. I guess it won't spent me too much time to pick them up again and to study a new programming language. If you think you need an extra hand, tell me what i need to learn in order to help.

**Comment by zelurker** [comment]
2016-02-16 9:26 GMT+01:00 Agijnnuwy notifications@github.com:

> Well... If you type debian steam and libgl in yahoo, you can see this is
> not a problem which only i got, all the debian 64 bit user got the similar
> problem. I tried to slove the problem following the official guide by
> installing the nvidia driver and the system is broken as the result and i
> have to reinstall Debian in to my computer.
> 
> Oh là là, it's only basic usage of your distribution, but since I don't get
> this kind of message too often, here you go :
> on your preferred search engine type "nvidia driver", it will bring you to
> the nvidia web site, fill in the form. For operating system it should be
> "linux 64 bits" from what you said. It should find version 361.28, download
> it. Once you have it make it executable (chmod +x).
> Now shutdown your graphical environment, you know how to do that, right ?
> Otherwise go and read some doc about your distribution... or search about
> this on the web if you are on a hurry, but you should really read some more
> about it in this case.
> Now from the text mode console lauch the file you just downloaded as root,
> it should be  NVIDIA-Linux-x86_64-361.28.run
> It will lead you through installation, at a time it asks if you want to
> install the 32 bit library with yes being the default, so you just have to
> type the return key to install it.
> When it finishes, it's done, you have your 32 bit libGL.so.1.
> And by the way you don't need to reinstall your whole system if you just
> break your graphical environment, keep this file you'll just have to
> relaunch it next time this happens to you !
> 
> If it is really a problem which can't be solved, i guess i have to run the
> windows version under wine. But the reason why i choose to use raine
> instead of mame, which is much more popular and is able to support the
> emulation of much more games (sorry to say that, but that is the truth), is
> beacause, mame no longer provide updates to the debian user and the latest
> version of mame on debian is v0.154(released two years ago) which it is
> v0.170 already on windows and ubuntu. raine is kind of the only active(by
> means of updataing) arcade emulator on debian. if would be so kickass if i
> need to run the only active elumator using wine or the old versions.

Yeah you can also compile mame on your system, it takes time because it's
huge, but it's easy to do, just download the sources, extract them, cd to
the directory, and normally you just have to type make.

**Comment by Agijnnuwy** [comment]
> An emulator is quite hard to program though, you need at least C knowledge, then read the source, see how it works and try to change things to your liking, eventually ask questions in the forum if you have problems, that's how it works in open source world !

Can you be more specific, I see so many files in the sources file folder and which shall I start with? I can basically understand what some of the files trying to achieve but I am a little confused about how these files connects with each other.

**Comment by zelurker** [comment]
the categories are in directories, game drivers in games, main functions in
root directory, sdl specific in sdl, 68000 emulator in 68000, etc...
You have to be curious and strong willed for that, it requires a lot of
time and it's not easy.

2016-02-16 16:49 GMT+01:00 Agijnnuwy notifications@github.com:

**Comment by Agijnnuwy** [comment]
Got it.

By the way is there any link to download the magazine and if its still updating.

**Comment by zelurker** [comment]
Which magazine ? zzap!raine ? Only online afaik...

2016-02-17 0:58 GMT+01:00 Agijnnuwy notifications@github.com:

**Comment by Agijnnuwy** [comment]
I see
