### ISSUE TITLE
Zipped Neo Geo CD games and CD audio tracks

### ISSUE THREAD

**Issue by piratesephiroth** [zelurker/raine#66]
It seems that there isn't a guide on how to make zipped Neo Geo CD games to work.
I understood that the main track has to be extracted so I can get the games to run but they have no music because the emulator just reports that the audio tracks cannot be found.
What do we do with the CD audio tracks so they work with zipped Neo Geo CD games?

**Comment by zelurker** [comment]
You know there is a web site ?
Anyway common sense : if it doesn't work with a zipped game, start by unzipping it.
Now if you want to save some disk space, the most efficient way is to extract the files from the iso, put them into a zip file, and encode the audio tracks either to mp3 or ogg. See the tons of messages about all this on the web site. Sorry I don't like writing docs, and nobody wanted to do it... !

**Comment by piratesephiroth** [comment]
If by "site" you mean the forums, I tried registering an account there before coming here but it doesn't seem to want to send me the activation email. Or maybe it takes days, I dunno.

I don't really want to save disk space, it's just that it seems better to pack everything in a single file.

The game works as iso + wav files, so I understand that the emulator is able to detect the tracks without a cue file;.
My problem isn't about how to make the game work, it's just about making it run from a zip file with working CD audio.
I spent some time searching and didn't find anything on the forums or anywhere else.

I even tried making a zip containing the extracting track 1 files in a "Track 01" folder and the remaining audio files next to it, to mimic the non-zipped structure. The game did work but the audio tracks still could not be detected.
The emulator's messages say "Could not find audio track" so it makes me believe there's a proper way to do it.

**Comment by zelurker** [comment]
Well you can either give a cue file, in this case the files referenced by
the cue file are supposed to be available in the same directory, that's
what most neocd backups use.
Or you can put an iso + some audio files in a directory without any cue
file. In this case the audio tracks need to have a number easy to
understand, like track02.wav or .mp3 or .ogg or .flac. Just point to the
iso and it will find everything.
Or you can extract the contents on this iso to a zip file, the audio tracks
must have the same format as the previous scenario, in this case point to
the zip file, it should contain an ipl.txt file, that's what a neocd game
uses to know what to load to boot.
Some neocd backups have the data + the audio tracks in the same file, but
in this case there is a cue file to describe this, it's supported too.
Point to the cue file.

But you can't give just a zip which would contain everything, for once
because if it's a zip, it expects to find an ipl.txt file in it, and for 2,
the audio tracks can't be read from inside an archive, I didn't try
libarchive to do that.
So usually neocd games use their own directory with at least 2 files in it,
but there can be more. The audio tracks can also be placed in a neocd.mp3
directory in this directory for compatibility with an old neocd emulator...
but everyone places everything in the same dir usually.


Le mar. 5 déc. 2023 à 00:15, piratesephiroth ***@***.***> a
écrit :

**Comment by zelurker** [comment]
Robert from the forum asks the user you tried to use, he says there is currently a problem with gmail and it never works...

**Comment by zelurker** [comment]
... and Robert validated the 4 last accounts which didn't reply to their validation email, so you were probably one of them.
