### ISSUE TITLE
Question about config file

### ISSUE THREAD

**Issue by Tartifless** [zelurker/raine#69]
Hello,
I cannot seem to find the raine config file (windows), i installed both 32 and 64 bits version, and the only file i see in the config folder is debug_dips.txt.

Is Raine portable or is the config file stored in another place ? 

Is there somewhere documentation about the command line arguments available ?

**Comment by zelurker** [comment]
the config file is created when you quit with the quit command, if you quit
by closing the window, no config file !

raine -h if you have a terminal to see the output, in windows you'll
probably have to redirect the output to a file : raine32 > output.

**Comment by Tartifless** [comment]
Indeed, raine -h gives a black screen and freezes raine.

One question though, when changing sound driver to directsound, the config file is correct but the interface always shows wasapi upon restart, even though configuration states directsound.
Which is correct ? The displayed value in the interface or the one in the configuration file ?

**Comment by zelurker** [comment]
Le mar. 18 juin 2024 à 18:24, Ben. S. ***@***.***> a écrit :

> Indeed, raine -h gives a black screen and freezes raine.
>
No black screen nor freeze here :
[image: Screenshot 2024-06-18 200340.png]
 Actually even if the window title is power shell, it's from cmd.exe. For
some reason power shell eats the output when trying to redirect to a file.
I'll attach the obtained log file then... !

> One question though, when changing sound driver to directsound, the config
> file is correct but the interface always shows wasapi upon restart, even
> though configuration states directsound.
> Which is correct ? The displayed value in the interface or the one in the
> configuration file ?
>
Something I didn't know !
I'll have to check how the driver setting is restored, it still runs its
autodetection when launched that's why your directsound is replaced by
wsapi when you launch it.
Well if you really want directsound you can select it before loading a
game, but normally it's useless, wsapi has become the default a very long
time ago in windows, I think directsound as the default must date of before
windows 7.

**Comment by zelurker** [comment]
And I forgot to attach the log file...
By the way it's not the latest version here because I type this in windows,
and I mainly use linux most of the time, but I wanted to verify your freeze
+ black screen in windows... !

Le mar. 18 juin 2024 à 20:11, Emmanuel Anne ***@***.***> a
écrit :

>
>

**Comment by Tartifless** [comment]
Thanks for all the info, i took the example of sound driver but it seems to be a bad example as this is auto-detected.

Last question and i'll stop asking: is there a recommanded romset or a datfile somewhere for mame games ?

**Comment by zelurker** [comment]
Ah well sorry I don't use dat files !
But raine knows how to automatically load its roms from internet archive so
you shouldn't have any problem, and it should be compatible with the vast
majority of mame romsets, afaik.
